data:extend({
  {
    type = "recipe",
    name = "Infinite-Fuel",
    energy_required = 500,
    hidden = true,
    enabled = false,
    icon = "__InfiniteFuel__/graphics/infinite-fuel-1.png",
    icon_size = 256,
    subgroup = "intermediate-product",
    order = "q[InfiniteFuel]-a",
    ingredients = { { name = "nuclear-fuel", amount = 10, type = "item" } },
    results = { { name = "Infinite-Fuel", amount = 1, type = "item" } }
  },
  {
    type = "recipe",
    name = "Boosted-Infinite-Fuel",
    energy_required = 1000,
    hidden = true,
    enabled = false,
    icon = "__InfiniteFuel__/graphics/infinite-fuel-2.png",
    icon_size = 256,
    subgroup = "intermediate-product",
    order = "q[InfiniteFuel]-b",
    ingredients = { { name = "Infinite-Fuel", amount = 2, type = "item" } },
    results = { { name = "Boosted-Infinite-Fuel", amount = 1, type = "item" } }
  },
  {
    type = "recipe",
    name = "Ultra-Boosted-Infinite-Fuel",
    energy_required = 1500,
    hidden = true,
    enabled = false,
    icon = "__InfiniteFuel__/graphics/infinite-fuel-3.png",
    icon_size = 256,
    subgroup = "intermediate-product",
    order = "q[InfiniteFuel]-c",
    ingredients = { { name = "Boosted-Infinite-Fuel", amount = 2, type = "item" } },
    results = { { name = "Ultra-Boosted-Infinite-Fuel", amount = 1, type = "item" } }
  },
  {
    type = "recipe",
    name = "Reactor-Infinite-Fuel",
    energy_required = 2000,
    hidden = true,
    enabled = false,
    icons = { { icon = "__InfiniteFuel__/graphics/infinite-fuel-1.png", tint = { r = 0, g = 60, b = 0 } } },
    icon_size = 256,
    subgroup = "intermediate-product",
    order = "q[InfiniteFuel]-d",
    ingredients = { { name = "Infinite-Fuel", amount = 2, type = "item" } },
    results = { { name = "Reactor-Infinite-Fuel", amount = 1, type = "item" } }
  },
  {
    type = "recipe",
    name = "kr-Infinite-Fuel",
    energy_required = 1000,
    hidden = true,
    enabled = false,
    icons = { { icon = "__InfiniteFuel__/graphics/infinite-fuel-2.png", tint = { r = 255, g = 69, b = 0 } } },
    icon_size = 256,
    subgroup = "intermediate-product",
    order = "q[InfiniteFuel]-e",
    ingredients = { { name = "Infinite-Fuel", amount = 2, type = "item" } },
    results = { { name = "kr-Infinite-Fuel", amount = 1, type = "item" } }
  },
})
